//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MontCrest_Task_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MontCrestEntities : DbContext
    {
        public MontCrestEntities()
            : base("name=MontCrestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StudentRegistration> StudentRegistrations { get; set; }
    
        public virtual ObjectResult<sp_checklogin_Result> sp_checklogin(string scode, string pass)
        {
            var scodeParameter = scode != null ?
                new ObjectParameter("scode", scode) :
                new ObjectParameter("scode", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_checklogin_Result>("sp_checklogin", scodeParameter, passParameter);
        }
    }
}
