//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MontCrest_Task_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRegistration
    {
        public int sid { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Adharno { get; set; }
        public string Profile { get; set; }
        public string Role { get; set; }
    }
}
